### PR TITLE
WIP: attempt to replicate virtual dataset example

### PR DESCRIPTION
**Pull request by ggggggggg**
Don't merge this.

I was hoping someone could take a look at this and figure out what I'm doing wrong. 

I added `h5p_set_virtual` then I tried to replicate the example [h5_vds.c](https://support.hdfgroup.org/ftp/HDF5/examples/110/h5_vds.c). But I've failed. I get an error on the last line of `virtual.jl` stating "objects still in open object info set". Additionally, I seem to need a `dataspace` in which the dimensions are reversed from the example in line 38.

If I can help me figure it out, I'll try to create a slightly easier to use API for creating virtual datasets, at least in some easy cases.

### CODE REVIEW

**Comment by adambrewster** [comment]
This would be cool if you could get it to work.  A couple of things to note:
 - This package reverses the order of the dimensions to avoid reordering the data, so `start` should probably be `[0,i-1]`, and block should probably be `[VSDIM1, 1]`.  This fixed the issue noted on line 37.
 - After making that change, if you comment out the last two lines, it successfully creates the file, and h5dump can read it.
 - `h5open(h5->read(h5["VDS"]), "vds.h5")` fails for the file produced by julia and the file produced by the sample C code you linked.

**Comment by musm** [comment]
👍

**Comment by AStupidBear** [comment]
@ggggggggg Do you succeed in implementing this? Why do you close this? It's pretty useful.

**Comment by ggggggggg** [comment]
@AStupidBear The problem I was trying to solve with hdf5 + julia I've now solved in a different way, so I'm not planning to work on this anymore. You or anyone else is free to pick it up if you're interested.

**Comment by AStupidBear** [comment]
@adambrewster @ggggggggg Why does julia failed to load VDS dataset?

**Comment by AStupidBear** [comment]
@ggggggggg I have successfully created a virtual dataset using your script and loading it back by setting `fclose_degree` to `H5F_CLOSE_DEFAULT`. See [h5load](https://github.com/AStupidBear/HDF5Utils.jl/blob/c8b037de63f4d8b3457f953e89b8592067355818/src/io.jl#L42) in [HDF5Utils.jl](https://github.com/AStupidBear/HDF5Utils.jl)

**Pull request closed without merging**
