### PR TITLE
Allow negative step sizes in slab

### PR DESCRIPTION
**Pull request by musm**
fix https://github.com/JuliaIO/HDF5.jl/issues/581

### CODE REVIEW

**Comment by musm** [comment]
cc @rafaqz

**Comment by musm** [comment]
yeah I don't know why this fails on windows, but I don't think this PR should work?

**Comment by rafaqz** [comment]
Weird that this just works! but also great, I thought it would need an intermediate op. Do you think the performance would be similar to regular indexing? I'm wondering wether to do this by default in GeoData.jl to standardise dimension order.

**Comment by musm** [comment]
Yeah it's odd it just works because it does a convert of the Int to an UInt, which HDF5 somehow understands means negative indexing. Maybe this is because of the two's complements?

Performance is identical, so no hit. 

Note there are some Cmake build failure that prevent windows CI from running.

**Pull request closed without merging**
