### PR TITLE
Use Refs instead of Vectors

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by musm** [comment]
Is there an advantage to having this is global const refs as opposed to local variables in the corresponding functions?

**Comment by musm** [comment]
bump

**Comment by simonster** [comment]
In principle, it would be better if these were local variables, but at the moment that would incur allocation and GC overhead that I don't think we want. IIRC the `HDF5ReferenceObj` constructor is used extensively by JLD.

**Comment by musm** [comment]
Thank you.  Yeah I observed a noticeable decrease in performance, when I tried local variables.

**Pull request merged**
