### PR TITLE
Update LICENSE.txt

### PR DESCRIPTION
**Pull request by musm**
cc @timholy, @simonster, @tshort, Konrad Hinsen (wasn't able to find contact info) for approval

### CODE REVIEW

**Comment by musm** [comment]
This was brought up because of comment https://github.com/JuliaIO/HDF5.jl/pull/875#discussion_r754435502 where an existing  contributor wanted to add their name to the license in a PR.

The addition here parallels the Julia language license wording, so I think it's reasonable.

**Comment by mkitti** [comment]
Konrad Hinsen is @khinsen , I believe. However, it is not clear to me if he made a direct contribution or perhaps someone added him because some of the code was derived from his code. I have not found a direct contribution in the commit log.

**Comment by tshort** [comment]
I approve. I'd also remove my name and have that fall under contributors (my contributions were small).

**Comment by mkitti** [comment]
There's some early logs of who contributed what here:
https://juliaio.github.io/HDF5.jl/stable/#Credits

**Comment by khinsen** [comment]
@mkitti The [very first commit](https://github.com/JuliaIO/HDF5.jl/commit/981c24d73e55e7de3f9179e17a33ebbbea865942) came from me (plus a few more). I started HDF5.jl both to experiment with Julia's FFI and because all of the data I'd possibly want to work on in Julia was stored in HDF5 files. But I never went beyond the minimal code required to do my experiments. Then @timholy took over and did much more substantial work. From today's perspective, my contribution to HDF5.jl is ridiculously small.

**Comment by mkitti** [comment]
> @mkitti The [very first commit](https://github.com/JuliaIO/HDF5.jl/commit/981c24d73e55e7de3f9179e17a33ebbbea865942) came from me (plus a few more). I started HDF5.jl both to experiment with Julia's FFI and because all of the data I'd possibly want to work on in Julia was stored in HDF5 files. But I never went beyond the minimal code required to do my experiments. Then @timholy took over and did much more substantial work.

Thanks for illuminating us. I was trying to use Github's tools to search the log, but I see that would not have worked since it didn't link your Github account. I did find you in the credits above. Thanks again for starting this.

This does point out that Github's contributor list may be incomplete. It may be useful to compile a list independent of Github.

**Comment by musm** [comment]
How about something like:
```
Copyright (c) 2012-2021: Timothy E. Holy, Simon Kornblith, and contributors.
Contributor list: https://github.com/JuliaIO/HDF5.jl/contributors
Additional contributors include: Konrad Hinsen, Tom Short
```

**Comment by tshort** [comment]
My name's not warranted as "additional contributors".

**Comment by khinsen** [comment]
Nor is mine.

**Comment by musm** [comment]
I have everyone's approval, save for @timholy.

**Comment by timholy** [comment]
Approved! Sorry for being slow.

**Pull request merged**
