### PR TITLE
Fix #379

### LINKED ISSUE #379: Not yet supported
Hi, I would like to read the timestamps of the attached file and get an "Not yet supported" error. Is there a way to just extract the column with the timestamp? Will this be supported in future?
Thanks, Lukas

[example.h5.zip](https://github.com/JuliaIO/HDF5.jl/files/850928/example.h5.zip)

### PR DESCRIPTION
**Pull request by tknopp**
Fixes #379 by simple increasing the membersize field. I am actually not sure what is correct here. Maybe directly 64bit?

### CODE REVIEW

**Comment by ararslan** [comment]
I looked at the HDF5 documentation on [compound types](https://support.hdfgroup.org/HDF5/Tutor/compound.html) a bit and it doesn't specify a limit on the size of members, so I wonder what the rationale was for using `UInt8` here. Apparently this `membersize` vector was introduced in https://github.com/JuliaIO/HDF5.jl/pull/365, so maybe @grahamrow has some insight.

**Comment by simonster** [comment]
`H5Tget_size` returns a `Csize_t`, but given that the HDF5 file format encodes the size of the type with 4 bytes, a `UInt32` is sufficient.

**Comment by tknopp** [comment]
Updated according to @simonster suggestion.

I no can read the dataset from https://sourceforge.net/projects/ismrmrd/files/data/ although unfortunately, the returned data is still not what it is supposed to be. h5py seems to load it correctly. But I actually cannot understand howto correctly interpret the data. Seems to be an immutable embedded into an HDF5 file.

**Comment by tknopp** [comment]
moved discussion on specific dataset and followup problems to #426.

**Comment by musm** [comment]
@tknopp  care to add the failing example as a test here?  FYI 32-bit windows failure is unrelated

**Comment by tknopp** [comment]
My test data can still not be loaded (see #426) so that is not suitable for a test case.

**Pull request merged**
