### PR TITLE
Use @static if for OS-specific code sections

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by yuyichao** [comment]
The static is not needed

**Comment by eschnett** [comment]
Does the `@static` hurt, or should I leave it in?

**Comment by yuyichao** [comment]
It hurts as in it is confusing so they should be removed

**Comment by eschnett** [comment]
The Appveyor failure seems to be the usual timeout and is likely unrelated.

**Comment by yuyichao** [comment]
LGTM, the Compat version is already high enough.

**Pull request merged**
