### PR TITLE
Add `isempty` for HDF5Dataset

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by andyferris** [comment]
bump

**Comment by tkelman** [comment]
could use a test

**Comment by musm** [comment]
@ggggggggg Care to add a test for this ?

**Comment by ggggggggg** [comment]
I'd be happy to, though I don't know what is the best way. I guess there is a privilege level where I could edit the PR? It says there is a conflict anyway, and it's only one word, so it's easier to just make a new PR and reference this. I'll just do that 

Also I don't think it is possible to create an HDF5Dataset with length zero, so this equivalent to `isempty(::HDF5Dataset) == false`.

**Pull request closed without merging**
