### PR TITLE
Move FileIO support into extension

### PR DESCRIPTION
**Pull request by topolarity**
This moves one of the two remaining uses of Requires.jl into a pair of extensions.

### CODE REVIEW

**Comment by topolarity** [comment]
Invalidations check appears to be an unrelated failure

**Comment by mkitti** [comment]
@simonbyrne @musm any thoughts about this pull request? Does this require a version bump?

**Review by simonbyrne — APPROVED** [review]

**Comment by mkitti** [comment]
I will try to sort these out this weekend.

**Comment by mkitti** [comment]
I'm leaning towards dropping Requires entirely with 0.18

**Pull request merged**
