### PR TITLE
Fix mmap support for windows

### PR DESCRIPTION
**Pull request by tknopp**
This is a test to fix mmap support on windows.

### CODE REVIEW

**Comment by tknopp** [comment]
Test is successful. This is a workaround for the mmap issue on windows. Since the file descriptor that we get from HDF5 is not correct, I instead simply open the file again. To get the permissions of the original file open, I needed to wrap the `get_intent` method. 

This closes #89 and #357.

**Comment by tknopp** [comment]
appveyor on x86 has other issues. The other ones are green. 

Ping @musm for review.

**Comment by tknopp** [comment]
@musm @timholy any objections to merging and making a release? I am requiring this in my package https://github.com/MagneticParticleImaging/MPIFiles.jl which is supposed to also work on windows.

**Comment by musm** [comment]
I plan to take a closer look this tomorrow.

**Comment by musm** [comment]
So is the issue `prop = h5d_get_access_plist(checkvalid(obj).id)` incorrect?

**Comment by musm** [comment]
I don't really understand why 
`h5f_get_vfd_handle(obj.file.id, prop, ret)` 
gives the wrong result, do you?

**Comment by musm** [comment]
In any case, since it wasn't working before I plan to merge this soon, since something that works even though not ideal,  is better than it not working at all.

@tknopp  It would be good to leave some breadcrumbs for future reference, if someone wants to delve more deeply into a proper fix.

**Comment by tknopp** [comment]
> I don't really understand why
> `h5f_get_vfd_handle(obj.file.id, prop, ret)`
> gives the wrong result, do you?

No, if I would know that, I would have fixed it ;-)

My guess is that the file handle is not compatible with what Julia requires in the `fdio` function.

But I actually don't have access to Windows, so I am not really the best to work on the original issue.

I improved the documentation and this then should be good to go from my side. I would appreciate, if this could be integrated into the upcoming release.

**Comment by musm** [comment]
Fantastic thank you very much @tknopp for working on this !

**Comment by musm** [comment]
I plan a new release very soon with this.

**Pull request merged**
