### PR TITLE
Update for 0.7 and drop earlier releases

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by andreasnoack** [comment]
I'd recommend not adding a project file yet since CIBot can't handle project files yet. Except for that, I think it would great to have this merged soon since the Mac/windows problem are unrelated to this PR.

**Comment by musm** [comment]
@andreasnoack  It's not clear to me why we cannot add project files to this repo. Is there something special about HDF5 and CIBot? Any references or issue tracker. Thanks.

**Comment by musm** [comment]
@andreasnoack let me know if the Project file will be a problem and I can open a further PR to remove it.

**Comment by andreasnoack** [comment]
It is a problem but it has nothing to do with HDF5. CIBot still uses the old package manager and it fails when there are project files in the packages. Hence, we have been removing project files from many packages lately.

**Comment by andreasnoack** [comment]
E.g. https://github.com/JuliaGraphics/Colors.jl/pull/323 and https://github.com/JuliaLang/Compat.jl/pull/624

**Comment by musm** [comment]
thnx ref https://github.com/JuliaIO/HDF5.jl/pull/505

**Pull request merged**
