### PR TITLE
update for cross platform bindeps

### PR DESCRIPTION
**Pull request by rened**
needs the corresponding PR for BinDeps.jl, coming up.

### CODE REVIEW

**Comment by rened** [comment]
Tests fail because they need https://github.com/JuliaLang/BinDeps.jl/pull/130 ...

**Comment by timholy** [comment]
Thanks for this. If I don't notice when the BinDeps work gets merged and tagged, just ping me.

**Comment by musm** [comment]
Is this still relevant?

**Comment by rened** [comment]
I think we can close this.

**Pull request closed without merging**
