### PR TITLE
unpad fixed length strings in compound datatypes

### LINKED ISSUE #379: Not yet supported
Hi, I would like to read the timestamps of the attached file and get an "Not yet supported" error. Is there a way to just extract the column with the timestamp? Will this be supported in future?
Thanks, Lukas

[example.h5.zip](https://github.com/JuliaIO/HDF5.jl/files/850928/example.h5.zip)

### PR DESCRIPTION
**Pull request by kleinhenz**
This is a minor followup to #592. Now unpadding is applied to fixed length strings in compound datatypes to match the behavior of plain fixed length strings.  Should close #379. I found this oversight while reading the file linked in that issue.

### CODE REVIEW

**Comment by kleinhenz** [comment]
Just to be clear, compound datatypes with fixed length strings already work, this just applies the unpadding procedure in order to be consistent with the non compound case.

**Comment by musm** [comment]
lgtm

**Comment by musm** [comment]
This looks fairly uncontroversial, thank you!

**Comment by musm** [comment]
Should be published soon, thanks again!

**Pull request merged**
