### PR TITLE
Fix libtarget when building from source

### PR DESCRIPTION
**Pull request by carlobaldassi**
The build was broken without this change (tested on RHEL).

### CODE REVIEW

**Comment by carlobaldassi** [comment]
(Appveyor failure is unrelated.)

**Comment by simonster** [comment]
@eschnett Can you verify that this fix is correct?

**Comment by musm** [comment]
for me both this pr and master work on fedora 25

**Comment by iamed2** [comment]
Also occurs on Amazon Linux

**Comment by musm** [comment]
Ok I'm going to merge this since it seems to be fixing the issue  for several people ref https://github.com/JuliaIO/HDF5.jl/issues/324#issuecomment-299235750

**Pull request merged**
