### PR TITLE
homebrew/science/hdf5 deprecated in favour of hdf5.

### LINKED ISSUE #429: Incorrect hdf5 install with homebrew.
Looks like I'm `v0.6/Homebrew/deps/usr/Library/Taps/homebrew/homebrew-science/hdf5.rb` doesn't existing in homebrew anymore and the only valid file is `v0.6/Homebrew/deps/usr/Library/Taps/homebrew/homebrew-science/hdf5@1.8.rb`. There's also a warning stating `Use hdf5 instead of deprecated homebrew/science/hdf5`, so maybe we should just switch to that?

[Failing travis build](https://travis-ci.org/JuliaIO/HDF5.jl/jobs/254590267)

### PR DESCRIPTION
**Pull request by rofinn**
Should close #429

### CODE REVIEW

**Comment by omus** [comment]
Nightly failures look like you require a new release of LibExpat.jl: https://github.com/JuliaIO/LibExpat.jl/pull/80

**Comment by musm** [comment]
> There's also a warning stating Use hdf5 instead of deprecated homebrew/science/hdf5

I don't see that in the travis logs?

Thanks. If no one else beats me to it or has objections will merge in a few days.

**Comment by rofinn** [comment]
Thanks. Sorry, I didn't realize till just now that I could link to specific lines in the travis build logs. https://travis-ci.org/JuliaIO/HDF5.jl/jobs/254590267#L761

**Comment by ssfrr** [comment]
@musm it might be worth merging (and tagging a release) on the sooner side unless there are concerns, as currently this breaks package installation. It seems that perhaps the deprecation period in Homebrew is over.

**Comment by musm** [comment]
Now tagged and in metadata.jl

**Pull request merged**
