### PR TITLE
docs: Instructions on how to read value of attribute

### PR DESCRIPTION
**Pull request by johnbcoughlin**
This had me confused earlier this week.

### CODE REVIEW

**Comment by musm** [comment]
Sorry I didn't see this earlier, lgtm.

**Comment by musm** [comment]
Also we added new syntax to make reading simpler, see https://github.com/JuliaIO/HDF5.jl/issues/824

**Comment by johnbcoughlin** [comment]
Good call. Updated!

**Comment by musm** [comment]
Thanks again!

**Pull request merged**
