### PR TITLE
export functions of eltype and isempty

### PR DESCRIPTION
**Pull request by jingpengwu**
currently, can not use these two functions.
also fix https://github.com/JuliaIO/HDF5.jl/issues/167

### CODE REVIEW

**Comment by eschnett** [comment]
Since HDF5 imports `eltype` and `isempty`, the respective definitions are already methods for `Base.eltype` and `Base.isempty`, and thus do not need to be exported.

**Comment by jingpengwu** [comment]
but I can not use eltype and isempty function without this modification. I already checkout the code from `master`.

**Comment by eschnett** [comment]
Both are working fine for me. Can you post an example to reproduce your problem?

**Comment by musm** [comment]
can someone close this?

**Comment by jingpengwu** [comment]
OK, I'll close this .

**Comment by musm** [comment]
both are also working fine for me (try a `Pkg.update`, if not)

**Pull request closed without merging**
