### PR TITLE
test more Julia versions on AppVeyor

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by timholy** [comment]
Note the AppVeyor failure.

**Comment by tkelman** [comment]
Something is up, it passed 11 hours ago: https://ci.appveyor.com/project/timholy/hdf5-jl/build/1.0.941/job/dorh09na3kgww0hf (this is why having a history of daily scheduled builds is so useful)

Will look into it locally.

**Comment by tkelman** [comment]
Silly me, it's because I removed the `-F`.

**Comment by timholy** [comment]
Still an error, but I don't know if it's meaningful.

**Comment by tkelman** [comment]
Looks like a connectivity thing. Either restart or merge?

**Pull request merged**
