### PR TITLE
Fixed ASCII vs UTF8 errors with Julia v0.5 String

### LINKED ISSUE #332: Error: Reading Attribute String
When loading a string (not unicode) attribute from a HDF5 file, the following error is thrown:

`ERROR: MethodError: no method matching unsafe_string(::Array{UInt8,1})`

Full error context:

``` julia
julia> h5readattr("bar.h5", "foo")

HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 139787026885632:
  #000: ../../../src/H5A.c line 642 in H5Aread(): unable to read attribute
    major: Attribute
    minor: Read failed
  #001: ../../../src/H5Aint.c line 641 in H5A_read(): unable to convert between src and dst datatypes
    major: Attribute
    minor: Feature is unsupported
  #002: ../../../src/H5T.c line 4548 in H5T_path_find(): no appropriate function for conversion path
    major: Datatype
    minor: Unable to initialize object
ERROR: MethodError: no method matching unsafe_string(::Array{UInt8,1})
Closest candidates are:
  unsafe_string(::Cstring) at c.jl:187
  unsafe_string(::Union{Ptr{Int8},Ptr{UInt8}}) at strings/basic.jl:56
  unsafe_string(::Union{Ptr{Int8},Ptr{UInt8}}, ::Integer) at strings/basic.jl:52
 in h5a_get_name(::Int32) at ~/.julia/v0.5/HDF5/src/plain.jl:2153
 in h5a_read(::Int32, ::Int32, ::Array{Ptr{UInt8},1}) at ~/.julia/v0.5/HDF5/src/plain.jl:2111
 in read(::HDF5.HDF5Attribute, ::Type{String}) at ~/.julia/v0.5/HDF5/src/plain.jl:1294
 in read(::HDF5.HDF5Attribute) at ~/.julia/v0.5/HDF5/src/plain.jl:1213
 in collect(::Base.Generator{Array{String,1},HDF5.##3#4}) at ./array.jl:307
 in h5readattr(::String, ::String) at ~/.julia/v0.5/HDF5/src/plain.jl:673
```

### PR DESCRIPTION
**Pull request by andyferris**
There is some confusion with encodings in Julia v0.5 since the `String` datatype is designed to represent both UTF8 and ASCII data. LibHDF5 is a little picky (e.g. it won't populate a UTF8 string with ASCII data, for some reason) and if the `cset` is incorrect then an error results when loading ASCII strings on Julia v0.5 (which e.g. makes it incompatible with other loaders/saves, including h5py).

There appears to be a deeper connection in the package assuming there is a well defined mapping from Julia datatypes to HDF5 string encodings, which just isn't true anymore. These changes represent more of a band-aid fix.

Fixes #332
Replaces #337

### CODE REVIEW

**Comment by andyferris** [comment]
I'm not sure on a unit test at the moment since I don't know a *convenient* way of writing an ASCII attribute on Julia 0.5 - help appreciated.

**Comment by andyferris** [comment]
Travis failure seems to be related to DataFrames on Julia v0.5 nightly.

**Comment by c42f** [comment]
> a convenient way of writing an ASCII attribute on julia-0.5

Presumably it wouldn't be too hard to do this in a non-convenient way using the low level interface?

**Comment by andyferris** [comment]
bump

**Comment by andyferris** [comment]
Rebased.

**Comment by musm** [comment]
@timholy does this look ok? Planning on merging in a day or 2

**Comment by musm** [comment]
Is there an easy way to test this. Can we adapt the issue for a test?

**Comment by ggggggggg** [comment]
You can use the command line tool `h5import` to make an appropriate test hdf5 file for reading. Example code:
```julia
using HDF5

fname = "hworld"

open(fname,"w") do f
  write(f,"Hello World")
end

configname = "config"
open(configname,"w") do f
  write(f,"HDF5 \"test\" {
GROUP \"\\\" {
   DATASET \"test\" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      }
   }
}
}")
end

outname = "out"
run(`h5import $fname -c $configname -o $outname`)

h5 = h5open(outname,"r")
read(h5["dataset0"])
```

**Comment by ggggggggg** [comment]
Alternativley you could download [h5ex_t_string.h5](https://support.hdfgroup.org/ftp/HDF5/examples/files/exbyapi/h5ex_t_string.h5) from the hdf5 group and include it. It probably would be a reasonable idea to include tests for reading [every file on this page](https://support.hdfgroup.org/HDF5/examples/api18-c.html) actually.

**Comment by andyferris** [comment]
The python string seems to be variable length and null terminated. I'll just add an example .h5 file like this to the `/test` directory.

**Comment by musm** [comment]
restarted ci, failure was a gzip download

**Comment by andyferris** [comment]
Seems to be passing now?

**Comment by musm** [comment]
Sans any objection, will merge this tomorrow

**Pull request merged**
