### PR TITLE
Drop 0.4

### PR DESCRIPTION
**Pull request by musm**
Will help to simplify string handling. Since 0.6 is soon looming might as well.

Close https://github.com/JuliaIO/HDF5.jl/issues/356

Helps with https://github.com/JuliaIO/HDF5.jl/pull/340  cc @andyferris

### CODE REVIEW

**Comment by andyferris** [comment]
Cool :)

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
thoughts?

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
any opinions on this?

**Comment by timholy** [comment]
I think it's a good idea. @musm, the prize for your patience in being such a good caretaker should arrive in your inbox shortly. Thanks for everything you're doing across many packages!

**Pull request merged**
