### PR TITLE
fix depwarns

### PR DESCRIPTION
**Pull request by abhijithch**
Fixes deprecation warning for `Julia v'0.5'`.

### CODE REVIEW

**Comment by eschnett** [comment]
I heard the dependency warnings are one reason why Appveyor is so slow. Could you update this PR, correcting the Travis and Appveyor errors?

**Comment by abhijithch** [comment]
After fixing deprecation warnings too the Appveyor is taking a long time.

**Comment by timholy** [comment]
Looks like the reason is there are still some deprecation warnings. If they're all silenced on your version of julia, perhaps check to see how old your version is. (Things move fast!)

**Comment by eschnett** [comment]
I still see a lot of deprecation warnings. These may come from other packages, e.g. `Blosc` or `Compat` (!). I say this looks good; let's apply it.

**Comment by timholy** [comment]
Looks like the `unsafe_string` transition we need for the most recent julia isn't even in Compat yet. So merging is reasonable.

**Comment by timholy** [comment]
Thanks a lot, @abhijithch!

**Comment by abhijithch** [comment]
Hi @timholy, I think the `unsafe_string` is merged to master with latest Julia nightly. I was planning to send another PR with the necessary changes, I needed a small clarification which is,  we need to use `unsafe_string` instead of `bytestring` and places where `String()` behaves like constructor leave those as is.  Is this the right approach? Thanks.

**Comment by yuyichao** [comment]
Needs https://github.com/JuliaLang/Compat.jl/pull/224

**Pull request merged**
