### PR TITLE
Use HDF5_jll

### PR DESCRIPTION
**Pull request by musm**
close https://github.com/JuliaIO/HDF5.jl/issues/594

### CODE REVIEW

**Comment by musm** [comment]
Are we okay with not providing a manual compilation fallback? I'm not sure on the best way to integrate that option.

**Comment by staticfloat** [comment]
It's fine with me, but someone who is a maintainer of this package should probably speak up about how important that is.  @timholy perhaps?

**Comment by musm** [comment]
@timholy hasn't maintained this package for over several years. I'm basically acting like the janitor on this package trying to do my best with keeping it workable...

**Comment by staticfloat** [comment]
Ah, my bad.  Then I'd say just do whatever makes it easier for you to maintain.  :)

**Comment by musm** [comment]
We will need to figure out how to add a fallback manual compilation mode, but perhaps this is OK for now.

**Pull request merged**
