### PR TITLE
Rm plain.jl

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by tkelman** [comment]
much better this way, but could use a rebase to just the last 3 commits

**Comment by musm** [comment]
anything else to do here?

**Comment by tkelman** [comment]
Guess not. All existing PR's would have to be rebased, but maybe that's worth the cleanup?

**Comment by musm** [comment]
True. I  took a look and there are maybe ~3 PRs that would require a rebase, the others are trivial. It looks like many of the PRs are stale from October and before. Your call on what is best.

**Comment by andyferris** [comment]
We can rebase our ones from September/October - go ahead and merge. :)

By the way, they didn't become stale - those PRs were simply ignored by the maintainers... :(

**Comment by musm** [comment]
I can help rebase some of the PRs if that helps.

**Pull request merged**
