### PR TITLE
Fix shared array test

### PR DESCRIPTION
**Pull request by musm**
ref https://github.com/JuliaIO/HDF5.jl/pull/463

### CODE REVIEW

**Comment by bjarthur** [comment]
thanks!

**Comment by bjarthur** [comment]
also, while working on my own fix for this, i noticed what i think is a mistake in the tests.  the file `fn` actually exists at the time for [this test](https://github.com/JuliaIO/HDF5.jl/blob/master/test/plain.jl#L357), when the test purports to test what happens if it doesn't.

**Comment by musm** [comment]
agreed that looks like an error

**Comment by musm** [comment]
mind opening a PR for that fix?

**Pull request merged**
