### PR TITLE
MAT.jl and JLD.jl downstream integration testing (#662)

### PR DESCRIPTION
**Pull request by musm**
close https://github.com/JuliaIO/HDF5.jl/issues/661

### CODE REVIEW

**Comment by musm** [comment]
Which platforms should we run integration tests and julia version?
Currently I assume
- Julia 1.5 and nightly
- Ubunutu and x64 only

**Comment by musm** [comment]
Do we need this for JLD also? I believe that package is in maintenance mode

**Comment by jmert** [comment]
Yeah, this is the kind of thing I had in mind.

> Which platforms should we run integration tests and julia version?
I like to test against earliest supported [*], latest stable, and nightly Julia — so that'd be 1.3, 1.5, and nightly, as I understand it — but I'm willing to hear arguments for/against that. For this type of test, I also assume Linux-only will be good enough since this should be just testing the API-level integration between the packages. Any OS-specific behavior tests should happen within the regular test sets of the responsible package.

> Do we need this for JLD also? I believe that package is in maintenance mode
Not sure, I guess. I've gotten involved here mainly because I want to use HDF5 for a specific use case, and then I want to allow (through `@requires` hooks) importing of a sparse matrix by name with any of HDF5, MAT, JLD, and JLD2 — i.e. try to be as convenient as possible for the user. If JLD's not going to get upgraded for the v0.14 world, I guess I just drop support for that option since I probably am going to require and make use of the HDFv0.14 in my project (and JLD2 is still a very easy option for Julia users).

**Comment by musm** [comment]
> I like to test against earliest supported [*], latest stable, and nightly Julia — so that'd be 1.3, 1.5, and nightly, as I understand it — but I'm willing to hear arguments for/against that. For this type of test, I also assume Linux-only will be good enough since this should be just testing the API-level integration between the packages. Any OS-specific behavior tests should happen within the regular test sets of the responsible package.

Me too, but I think for integration testing it might be overkill on CI to test on all three versions? I only opted for 1.5 and nightly, but I don't mind either going for 1.3 (earliest) and nightly (latest) or all three. I don't have a strong preference TBH. 


> Not sure, I guess. I've gotten involved here mainly because I want to use HDF5 for a specific use case, and then I want to allow (through @requires hooks) importing of a sparse matrix by name with any of HDF5, MAT, JLD, and JLD2 — i.e. try to be as convenient as possible for the user. If JLD's not going to get upgraded for the v0.14 world, I guess I just drop support for that option since I probably am going to require and make use of the HDFv0.14 in my project (and JLD2 is still a very easy option for Julia users).

I'm happy to add JLD, but personally I don't use the package. Do tests pass with JLD on master HDF5? I guess I could test it out.

**Comment by musm** [comment]
I ended up trimming it just to 1.5, it's a lot of visual noise in the "checks" box to keep track of.

**Comment by musm** [comment]
Feel free to open further PR's on this if you think we should change it. For now it's certainly better than nothing. I think for now testing on one Julia version is ok, it will catch any glaring integration failures, which is what I think we want this for anyways.

**Pull request merged**
