### PR TITLE
Port non-breaking changes for 0.16.16

### LINKED ISSUE #1083: `maxdims` or `max_dims` in `dataspace()`
In `dataspaces.jl`, the documentation has `dataspace(dims::Tuple; maxdims::Tuple=dims)` while the actual code has `max_dims` as the keyword argument.

### LINKED ISSUE #1084: Using `Type` and `Dataspace` in `create_dataset()`
According to the documentation of `create_dataset(parent, path, datatype, dataspace; properties...)`, `datatype` can be either `Datatype` or `Type`, and `dataspace` can be either `Dataspace` or `Dims`. However, it throws an error if one uses `datatype::Type` with `dataspace::Dataspace`.

### PR DESCRIPTION
**Pull request by mkitti**
Cherry pick non-breaking changes from master to release-0.16

Cherry picked up to f3c942cf685b5e1906f20c2d6e1cdd1272a45228

- Fix _typed_load fast path for Julia 1.10 (currently nightly) (#1075)
- Add initial support for H5Dchunk_iter (#1031)
- Simplify formatter check (#1078)
- Fix #1083 maxdims -> max_dims in dataspace documentation (#1085)
- Update light and dark logos for readme (#1087)
- Fixup readme logo links and readme style (#1088)
- Upload curves directly instead of fonts for logo independence (#1089)
- Allow create_dataset to take a Type and Dataspace, Fix #1084 (#1086)
- Attempt to fix documentation (#1091)
- doc typo: attributes(parent), not attribute(parent) (#1095)

### CODE REVIEW

**Comment by mkitti** [comment]
@simonbyrne @musm I think we will need a 0.16.16 release for 1.10 compatability before we can push out 0.17.

**Comment by mkitti** [comment]
@musm I want to merge this as soon as possible since Julia 1.10 is now in beta. Any objections?

**Comment by musm** [comment]
LGTM! 

Rebase and merge as please

**Comment by musm** [comment]
Actually maybe a squash and merge would be easier for maintenance?

**Review by musm — APPROVED** [review]

**Pull request merged**
