### PR TITLE
Fixes create_dataset for compound types

### LINKED ISSUE #1068: Creating compound datasets is not working
I am happily using `write_dataset()` to dump compound structures using arrays of structs, but while I was writing an expandable cached write-out wrapper, I discovered that creating datasets is not working. Something is not propagated correctly because it complains that `Type Symbol has not have a definite size`.

Let me dump this issue (I'll also try to figure out what's wrong).

Probably related to https://github.com/JuliaIO/HDF5.jl/pull/1013 and see also the recent post on the Julia Discourse: https://discourse.julialang.org/t/hdf5-jl-variable-length-string/98808

```julia
julia> using HDF5  # v0.16.14

julia> struct Foo
         x::Int32
         y::Float32
       end

julia> f = h5open("test.h5", "w")
🗂️ HDF5.File: (read-write) test.h5

julia> d = create_dataset(f, "foo", Foo, (10,))  # the type Foo is not propagated correctly
ERROR: Type Symbol does not have a definite size.
Stacktrace:
  [1] sizeof(x::Type)
    @ Base ./essentials.jl:559
  [2] hdf5_type_id(#unused#::Type{Symbol}, isstruct::Val{true})
    @ HDF5 ~/.julia/packages/HDF5/HtnQZ/src/typeconversions.jl:71
  [3] hdf5_type_id(#unused#::Type{Symbol})
    @ HDF5 ~/.julia/packages/HDF5/HtnQZ/src/typeconversions.jl:69
  [4] hdf5_type_id(#unused#::Type{Core.TypeName}, isstruct::Val{true})
    @ HDF5 ~/.julia/packages/HDF5/HtnQZ/src/typeconversions.jl:74
  [5] hdf5_type_id(#unused#::Type{Core.TypeName})
    @ HDF5 ~/.julia/packages/HDF5/HtnQZ/src/typeconversions.jl:69
  [6] hdf5_type_id(#unused#::Type{DataType}, isstruct::Val{true})
    @ HDF5 ~/.julia/packages/HDF5/HtnQZ/src/typeconversions.jl:74
  [7] hdf5_type_id(#unused#::Type{DataType})
    @ HDF5 ~/.julia/packages/HDF5/HtnQZ/src/typeconversions.jl:69
  [8] datatype(#unused#::Type{Foo})
    @ HDF5 ~/.julia/packages/HDF5/HtnQZ/src/typeconversions.jl:66
  [9] create_dataset(parent::HDF5.File, path::String, dtype::Type, dspace_dims::Tuple{Int64}; pv::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ HDF5 ~/.julia/packages/HDF5/HtnQZ/src/datasets.jl:103
 [10] create_dataset(parent::HDF5.File, path::String, dtype::Type, dspace_dims::Tuple{Int64})
    @ HDF5 ~/.julia/packages/HDF5/HtnQZ/src/datasets.jl:103
 [11] top-level scope
    @ REPL[7]:1

julia> foos = [Foo(1,2), Foo(3, 4)]
2-element Vector{Foo}:
 Foo(1, 2.0f0)
 Foo(3, 4.0f0)

julia> write_dataset(f, "foo", foos)

julia> f["foo"][:]
2-element Vector{NamedTuple{(:x, :y), Tuple{Int32, Float32}}}:
 (x = 1, y = 2.0)
 (x = 3, y = 4.0)

julia> d = create_dataset(f, "some_ints", Int, (10,))  # writing directly works fine
🔢 HDF5.Dataset: /some_ints (file: test.h5 xfer_mode: 0)
```

### PR DESCRIPTION
**Pull request by tamasgal**
A small fix of `create_dataset` which choked when passing your own `structs`.

Closes #1068

### CODE REVIEW

**Comment by mkitti** [comment]
You beat me to it.

**Comment by mkitti** [comment]
Could you look over #1067 ? I want merge this one and that one together and check the composition.

**Comment by tamasgal** [comment]
I confirm that all tests pass after merging this (#1069) into #1067.

**Comment by tamasgal** [comment]
Do you need anything else? `;)`

**Comment by mkitti** [comment]
OK the JLD tests finally passed. Let's merge.

**Comment by tamasgal** [comment]
What do you think about a patch release, now with the strings and this being fixed?

**Pull request merged**
