### PR TITLE
Change ccall wrapper signature of `h5a_iterate` and `h5l_iterate`

### LINKED ISSUE #814: Fatal error in Julia 1.4
After the latest update we started picking up a fatal error in the Julia 1.4 CI. Here is the log file 
https://github.com/NREL-SIIP/PowerSimulations.jl/runs/1880992442#step:5:478

This issue won't appear in Julia 1.5.2 or 1.5.3.

### PR DESCRIPTION
**Pull request by jmert**
Addresses comment from https://github.com/JuliaIO/HDF5.jl/pull/812#discussion_r575495220.

Fixes #814.

### CODE REVIEW

**Comment by musm** [comment]
LGTM

**Comment by jmert** [comment]
Change from having the `op_data` argument functionally exposed (and documented in the API reference) as `::Ptr{Cvoid}` to `::Any` is probably arguably a bug fix.

**Comment by jmert** [comment]
OK, CI passed on v1.4. I'll rebase to remove the CI change and push again.

**Comment by musm** [comment]
Thanks, I'll also make a new patch release with this fix.

**Pull request merged**
