### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by jw3126**
Can you tag a release? It would be pretty nice to be compatible with compat 4.

### CODE REVIEW

**Comment by mkitti** [comment]
What is compat 4?

**Comment by mkitti** [comment]
I think we at least need #956 and #958 before we release

**Comment by jw3126** [comment]
> What is compat 4?

What I meant was `Compat.jl` version 4. I had a situation where I installed a package that needs `Compat.jl` version 4 and HDF5.jl in a single environment. The result was that a very old version HDF5.jl got installed.

**Comment by musm** [comment]
@mkitti  all the recent changes constitute a patch release as they are all backwards compatible and no deprecation of the attribute interface has been incorporated yet.

**Pull request closed without merging**
